name: examen-workflow


on:
  push:
    branches:
      - nueva-caracteristica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Descargar el código
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2) Configurar Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      # 3) Ejecutar comandos Python
      - name: Instalar pytest
        run: pip install pytest

      - name: Ejecutar tests con pytest
        run: pytest test.py

      # 4) Construir la imagen Docker
      - name: Construir imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

